// flow-typed signature: 1768428e147d0f4748a81f4baa376327
// flow-typed version: <<STUB>>/js-given_v^0.0.11/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-given'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-given' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-given/cli' {
  declare module.exports: any;
}

declare module 'js-given/installJGivenReport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-given/cli.js' {
  declare module.exports: $Exports<'js-given/cli'>;
}
declare module 'js-given/index' {
  declare module.exports: $Exports<'js-given'>;
}
declare module 'js-given/index.js' {
  declare module.exports: $Exports<'js-given'>;
}
declare module 'js-given/installJGivenReport.js' {
  declare module.exports: $Exports<'js-given/installJGivenReport'>;
}
